# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'MenudoSeller' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

pod 'AWSS3', '~> 2.15.3' 
pod 'Alamofire', '~> 5.0' 
pod 'PusherSwift'
pod 'PushNotifications', '~> 0.10.1' 
pod "BouncyLayout"
end

